.PHONY: all
all: 1.json 2.json 3.json 4.json 5.json 6.json 7.json 8.json 9.json 10.json 11.json 12.json 13.json 14.json 15.json 16.json 17.json 18.json 19.json 20.json 21.json 22.json 23.json 24.json 25.json 26.json 27.json 28.json 29.json 30.json 31.json 32.json 33.json 34.json 35.json 36.json 37.json 38.json 39.json 40.json 41.json 42.json 43.json 44.json 45.json 46.json 47.json 48.json 49.json 50.json 51.json 52.json 53.json 54.json 55.json 56.json 57.json 58.json 59.json 60.json 61.json 62.json 63.json 64.json 65.json 66.json 67.json 68.json 69.json 70.json 71.json 72.json 73.json 74.json 75.json 76.json 77.json 78.json 79.json 80.json 81.json 82.json 83.json 84.json 85.json 86.json 87.json 88.json 89.json 90.json
1.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/1.json -o 1.json -l ../logs/1.log --rand-iters 1000000 --rand-max-secs 600
2.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/2.json -o 2.json -l ../logs/2.log --rand-iters 1000000 --rand-max-secs 600
3.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/3.json -o 3.json -l ../logs/3.log --rand-iters 1000000 --rand-max-secs 600
4.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/4.json -o 4.json -l ../logs/4.log --rand-iters 1000000 --rand-max-secs 600
5.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/5.json -o 5.json -l ../logs/5.log --rand-iters 1000000 --rand-max-secs 600
6.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/6.json -o 6.json -l ../logs/6.log --rand-iters 1000000 --rand-max-secs 600
7.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/7.json -o 7.json -l ../logs/7.log --rand-iters 1000000 --rand-max-secs 600
8.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/8.json -o 8.json -l ../logs/8.log --rand-iters 1000000 --rand-max-secs 600
9.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/9.json -o 9.json -l ../logs/9.log --rand-iters 1000000 --rand-max-secs 600
10.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/10.json -o 10.json -l ../logs/10.log --rand-iters 1000000 --rand-max-secs 600
11.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/11.json -o 11.json -l ../logs/11.log --rand-iters 1000000 --rand-max-secs 600
12.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/12.json -o 12.json -l ../logs/12.log --rand-iters 1000000 --rand-max-secs 600
13.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/13.json -o 13.json -l ../logs/13.log --rand-iters 1000000 --rand-max-secs 600
14.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/14.json -o 14.json -l ../logs/14.log --rand-iters 1000000 --rand-max-secs 600
15.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/15.json -o 15.json -l ../logs/15.log --rand-iters 1000000 --rand-max-secs 600
16.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/16.json -o 16.json -l ../logs/16.log --rand-iters 1000000 --rand-max-secs 600
17.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/17.json -o 17.json -l ../logs/17.log --rand-iters 1000000 --rand-max-secs 600
18.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/18.json -o 18.json -l ../logs/18.log --rand-iters 1000000 --rand-max-secs 600
19.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/19.json -o 19.json -l ../logs/19.log --rand-iters 1000000 --rand-max-secs 600
20.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/20.json -o 20.json -l ../logs/20.log --rand-iters 1000000 --rand-max-secs 600
21.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/21.json -o 21.json -l ../logs/21.log --rand-iters 1000000 --rand-max-secs 600
22.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/22.json -o 22.json -l ../logs/22.log --rand-iters 1000000 --rand-max-secs 600
23.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/23.json -o 23.json -l ../logs/23.log --rand-iters 1000000 --rand-max-secs 600
24.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/24.json -o 24.json -l ../logs/24.log --rand-iters 1000000 --rand-max-secs 600
25.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/25.json -o 25.json -l ../logs/25.log --rand-iters 1000000 --rand-max-secs 600
26.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/26.json -o 26.json -l ../logs/26.log --rand-iters 1000000 --rand-max-secs 600
27.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/27.json -o 27.json -l ../logs/27.log --rand-iters 1000000 --rand-max-secs 600
28.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/28.json -o 28.json -l ../logs/28.log --rand-iters 1000000 --rand-max-secs 600
29.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/29.json -o 29.json -l ../logs/29.log --rand-iters 1000000 --rand-max-secs 600
30.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/30.json -o 30.json -l ../logs/30.log --rand-iters 1000000 --rand-max-secs 600
31.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/31.json -o 31.json -l ../logs/31.log --rand-iters 1000000 --rand-max-secs 600
32.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/32.json -o 32.json -l ../logs/32.log --rand-iters 1000000 --rand-max-secs 600
33.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/33.json -o 33.json -l ../logs/33.log --rand-iters 1000000 --rand-max-secs 600
34.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/34.json -o 34.json -l ../logs/34.log --rand-iters 1000000 --rand-max-secs 600
35.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/35.json -o 35.json -l ../logs/35.log --rand-iters 1000000 --rand-max-secs 600
36.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/36.json -o 36.json -l ../logs/36.log --rand-iters 1000000 --rand-max-secs 600
37.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/37.json -o 37.json -l ../logs/37.log --rand-iters 1000000 --rand-max-secs 600
38.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/38.json -o 38.json -l ../logs/38.log --rand-iters 1000000 --rand-max-secs 600
39.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/39.json -o 39.json -l ../logs/39.log --rand-iters 1000000 --rand-max-secs 600
40.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/40.json -o 40.json -l ../logs/40.log --rand-iters 1000000 --rand-max-secs 600
41.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/41.json -o 41.json -l ../logs/41.log --rand-iters 1000000 --rand-max-secs 600
42.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/42.json -o 42.json -l ../logs/42.log --rand-iters 1000000 --rand-max-secs 600
43.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/43.json -o 43.json -l ../logs/43.log --rand-iters 1000000 --rand-max-secs 600
44.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/44.json -o 44.json -l ../logs/44.log --rand-iters 1000000 --rand-max-secs 600
45.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/45.json -o 45.json -l ../logs/45.log --rand-iters 1000000 --rand-max-secs 600
46.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/46.json -o 46.json -l ../logs/46.log --rand-iters 1000000 --rand-max-secs 600
47.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/47.json -o 47.json -l ../logs/47.log --rand-iters 1000000 --rand-max-secs 600
48.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/48.json -o 48.json -l ../logs/48.log --rand-iters 1000000 --rand-max-secs 600
49.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/49.json -o 49.json -l ../logs/49.log --rand-iters 1000000 --rand-max-secs 600
50.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/50.json -o 50.json -l ../logs/50.log --rand-iters 1000000 --rand-max-secs 600
51.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/51.json -o 51.json -l ../logs/51.log --rand-iters 1000000 --rand-max-secs 600
52.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/52.json -o 52.json -l ../logs/52.log --rand-iters 1000000 --rand-max-secs 600
53.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/53.json -o 53.json -l ../logs/53.log --rand-iters 1000000 --rand-max-secs 600
54.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/54.json -o 54.json -l ../logs/54.log --rand-iters 1000000 --rand-max-secs 600
55.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/55.json -o 55.json -l ../logs/55.log --rand-iters 1000000 --rand-max-secs 600
56.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/56.json -o 56.json -l ../logs/56.log --rand-iters 1000000 --rand-max-secs 600
57.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/57.json -o 57.json -l ../logs/57.log --rand-iters 1000000 --rand-max-secs 600
58.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/58.json -o 58.json -l ../logs/58.log --rand-iters 1000000 --rand-max-secs 600
59.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/59.json -o 59.json -l ../logs/59.log --rand-iters 1000000 --rand-max-secs 600
60.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/60.json -o 60.json -l ../logs/60.log --rand-iters 1000000 --rand-max-secs 600
61.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/61.json -o 61.json -l ../logs/61.log --rand-iters 1000000 --rand-max-secs 600
62.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/62.json -o 62.json -l ../logs/62.log --rand-iters 1000000 --rand-max-secs 600
63.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/63.json -o 63.json -l ../logs/63.log --rand-iters 1000000 --rand-max-secs 600
64.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/64.json -o 64.json -l ../logs/64.log --rand-iters 1000000 --rand-max-secs 600
65.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/65.json -o 65.json -l ../logs/65.log --rand-iters 1000000 --rand-max-secs 600
66.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/66.json -o 66.json -l ../logs/66.log --rand-iters 1000000 --rand-max-secs 600
67.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/67.json -o 67.json -l ../logs/67.log --rand-iters 1000000 --rand-max-secs 600
68.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/68.json -o 68.json -l ../logs/68.log --rand-iters 1000000 --rand-max-secs 600
69.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/69.json -o 69.json -l ../logs/69.log --rand-iters 1000000 --rand-max-secs 600
70.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/70.json -o 70.json -l ../logs/70.log --rand-iters 1000000 --rand-max-secs 600
71.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/71.json -o 71.json -l ../logs/71.log --rand-iters 1000000 --rand-max-secs 600
72.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/72.json -o 72.json -l ../logs/72.log --rand-iters 1000000 --rand-max-secs 600
73.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/73.json -o 73.json -l ../logs/73.log --rand-iters 1000000 --rand-max-secs 600
74.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/74.json -o 74.json -l ../logs/74.log --rand-iters 1000000 --rand-max-secs 600
75.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/75.json -o 75.json -l ../logs/75.log --rand-iters 1000000 --rand-max-secs 600
76.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/76.json -o 76.json -l ../logs/76.log --rand-iters 1000000 --rand-max-secs 600
77.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/77.json -o 77.json -l ../logs/77.log --rand-iters 1000000 --rand-max-secs 600
78.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/78.json -o 78.json -l ../logs/78.log --rand-iters 1000000 --rand-max-secs 600
79.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/79.json -o 79.json -l ../logs/79.log --rand-iters 1000000 --rand-max-secs 600
80.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/80.json -o 80.json -l ../logs/80.log --rand-iters 1000000 --rand-max-secs 600
81.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/81.json -o 81.json -l ../logs/81.log --rand-iters 1000000 --rand-max-secs 600
82.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/82.json -o 82.json -l ../logs/82.log --rand-iters 1000000 --rand-max-secs 600
83.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/83.json -o 83.json -l ../logs/83.log --rand-iters 1000000 --rand-max-secs 600
84.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/84.json -o 84.json -l ../logs/84.log --rand-iters 1000000 --rand-max-secs 600
85.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/85.json -o 85.json -l ../logs/85.log --rand-iters 1000000 --rand-max-secs 600
86.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/86.json -o 86.json -l ../logs/86.log --rand-iters 1000000 --rand-max-secs 600
87.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/87.json -o 87.json -l ../logs/87.log --rand-iters 1000000 --rand-max-secs 600
88.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/88.json -o 88.json -l ../logs/88.log --rand-iters 1000000 --rand-max-secs 600
89.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/89.json -o 89.json -l ../logs/89.log --rand-iters 1000000 --rand-max-secs 600
90.json:
	cargo +nightly run --manifest-path ../solver/Cargo.toml --release -- problem -i ../problems/90.json -o 90.json -l ../logs/90.log --rand-iters 1000000 --rand-max-secs 600
