.PHONY: all
all: 1.svg 2.svg 3.svg 4.svg 5.svg 6.svg 7.svg 8.svg 9.svg 10.svg 11.svg 12.svg 13.svg 14.svg 15.svg 16.svg 17.svg 18.svg 19.svg 20.svg 21.svg 22.svg 23.svg 24.svg 25.svg 26.svg 27.svg 28.svg 29.svg 30.svg 31.svg 32.svg 33.svg 34.svg 35.svg 36.svg 37.svg 38.svg 39.svg 40.svg 41.svg 42.svg 43.svg 44.svg 45.svg 46.svg 47.svg 48.svg 49.svg 50.svg 51.svg 52.svg 53.svg 54.svg 55.svg 56.svg 57.svg 58.svg 59.svg 60.svg 61.svg 62.svg 63.svg 64.svg 65.svg 66.svg 67.svg 68.svg 69.svg 70.svg 71.svg 72.svg 73.svg 74.svg 75.svg 76.svg 77.svg 78.svg 79.svg 80.svg 81.svg 82.svg 83.svg 84.svg 85.svg 86.svg 87.svg 88.svg 89.svg 90.svg

1.svg: ../problems/1.json ../solutions/1.json
	. venv/bin/activate && python3 vis_prob.py 1.svg ../problems/1.json ../solutions/1.json
2.svg: ../problems/2.json ../solutions/2.json
	. venv/bin/activate && python3 vis_prob.py 2.svg ../problems/2.json ../solutions/2.json
3.svg: ../problems/3.json ../solutions/3.json
	. venv/bin/activate && python3 vis_prob.py 3.svg ../problems/3.json ../solutions/3.json
4.svg: ../problems/4.json ../solutions/4.json
	. venv/bin/activate && python3 vis_prob.py 4.svg ../problems/4.json ../solutions/4.json
5.svg: ../problems/5.json ../solutions/5.json
	. venv/bin/activate && python3 vis_prob.py 5.svg ../problems/5.json ../solutions/5.json
6.svg: ../problems/6.json ../solutions/6.json
	. venv/bin/activate && python3 vis_prob.py 6.svg ../problems/6.json ../solutions/6.json
7.svg: ../problems/7.json ../solutions/7.json
	. venv/bin/activate && python3 vis_prob.py 7.svg ../problems/7.json ../solutions/7.json
8.svg: ../problems/8.json ../solutions/8.json
	. venv/bin/activate && python3 vis_prob.py 8.svg ../problems/8.json ../solutions/8.json
9.svg: ../problems/9.json ../solutions/9.json
	. venv/bin/activate && python3 vis_prob.py 9.svg ../problems/9.json ../solutions/9.json
10.svg: ../problems/10.json ../solutions/10.json
	. venv/bin/activate && python3 vis_prob.py 10.svg ../problems/10.json ../solutions/10.json
11.svg: ../problems/11.json ../solutions/11.json
	. venv/bin/activate && python3 vis_prob.py 11.svg ../problems/11.json ../solutions/11.json
12.svg: ../problems/12.json ../solutions/12.json
	. venv/bin/activate && python3 vis_prob.py 12.svg ../problems/12.json ../solutions/12.json
13.svg: ../problems/13.json ../solutions/13.json
	. venv/bin/activate && python3 vis_prob.py 13.svg ../problems/13.json ../solutions/13.json
14.svg: ../problems/14.json ../solutions/14.json
	. venv/bin/activate && python3 vis_prob.py 14.svg ../problems/14.json ../solutions/14.json
15.svg: ../problems/15.json ../solutions/15.json
	. venv/bin/activate && python3 vis_prob.py 15.svg ../problems/15.json ../solutions/15.json
16.svg: ../problems/16.json ../solutions/16.json
	. venv/bin/activate && python3 vis_prob.py 16.svg ../problems/16.json ../solutions/16.json
17.svg: ../problems/17.json ../solutions/17.json
	. venv/bin/activate && python3 vis_prob.py 17.svg ../problems/17.json ../solutions/17.json
18.svg: ../problems/18.json ../solutions/18.json
	. venv/bin/activate && python3 vis_prob.py 18.svg ../problems/18.json ../solutions/18.json
19.svg: ../problems/19.json ../solutions/19.json
	. venv/bin/activate && python3 vis_prob.py 19.svg ../problems/19.json ../solutions/19.json
20.svg: ../problems/20.json ../solutions/20.json
	. venv/bin/activate && python3 vis_prob.py 20.svg ../problems/20.json ../solutions/20.json
21.svg: ../problems/21.json ../solutions/21.json
	. venv/bin/activate && python3 vis_prob.py 21.svg ../problems/21.json ../solutions/21.json
22.svg: ../problems/22.json ../solutions/22.json
	. venv/bin/activate && python3 vis_prob.py 22.svg ../problems/22.json ../solutions/22.json
23.svg: ../problems/23.json ../solutions/23.json
	. venv/bin/activate && python3 vis_prob.py 23.svg ../problems/23.json ../solutions/23.json
24.svg: ../problems/24.json ../solutions/24.json
	. venv/bin/activate && python3 vis_prob.py 24.svg ../problems/24.json ../solutions/24.json
25.svg: ../problems/25.json ../solutions/25.json
	. venv/bin/activate && python3 vis_prob.py 25.svg ../problems/25.json ../solutions/25.json
26.svg: ../problems/26.json ../solutions/26.json
	. venv/bin/activate && python3 vis_prob.py 26.svg ../problems/26.json ../solutions/26.json
27.svg: ../problems/27.json ../solutions/27.json
	. venv/bin/activate && python3 vis_prob.py 27.svg ../problems/27.json ../solutions/27.json
28.svg: ../problems/28.json ../solutions/28.json
	. venv/bin/activate && python3 vis_prob.py 28.svg ../problems/28.json ../solutions/28.json
29.svg: ../problems/29.json ../solutions/29.json
	. venv/bin/activate && python3 vis_prob.py 29.svg ../problems/29.json ../solutions/29.json
30.svg: ../problems/30.json ../solutions/30.json
	. venv/bin/activate && python3 vis_prob.py 30.svg ../problems/30.json ../solutions/30.json
31.svg: ../problems/31.json ../solutions/31.json
	. venv/bin/activate && python3 vis_prob.py 31.svg ../problems/31.json ../solutions/31.json
32.svg: ../problems/32.json ../solutions/32.json
	. venv/bin/activate && python3 vis_prob.py 32.svg ../problems/32.json ../solutions/32.json
33.svg: ../problems/33.json ../solutions/33.json
	. venv/bin/activate && python3 vis_prob.py 33.svg ../problems/33.json ../solutions/33.json
34.svg: ../problems/34.json ../solutions/34.json
	. venv/bin/activate && python3 vis_prob.py 34.svg ../problems/34.json ../solutions/34.json
35.svg: ../problems/35.json ../solutions/35.json
	. venv/bin/activate && python3 vis_prob.py 35.svg ../problems/35.json ../solutions/35.json
36.svg: ../problems/36.json ../solutions/36.json
	. venv/bin/activate && python3 vis_prob.py 36.svg ../problems/36.json ../solutions/36.json
37.svg: ../problems/37.json ../solutions/37.json
	. venv/bin/activate && python3 vis_prob.py 37.svg ../problems/37.json ../solutions/37.json
38.svg: ../problems/38.json ../solutions/38.json
	. venv/bin/activate && python3 vis_prob.py 38.svg ../problems/38.json ../solutions/38.json
39.svg: ../problems/39.json ../solutions/39.json
	. venv/bin/activate && python3 vis_prob.py 39.svg ../problems/39.json ../solutions/39.json
40.svg: ../problems/40.json ../solutions/40.json
	. venv/bin/activate && python3 vis_prob.py 40.svg ../problems/40.json ../solutions/40.json
41.svg: ../problems/41.json ../solutions/41.json
	. venv/bin/activate && python3 vis_prob.py 41.svg ../problems/41.json ../solutions/41.json
42.svg: ../problems/42.json ../solutions/42.json
	. venv/bin/activate && python3 vis_prob.py 42.svg ../problems/42.json ../solutions/42.json
43.svg: ../problems/43.json ../solutions/43.json
	. venv/bin/activate && python3 vis_prob.py 43.svg ../problems/43.json ../solutions/43.json
44.svg: ../problems/44.json ../solutions/44.json
	. venv/bin/activate && python3 vis_prob.py 44.svg ../problems/44.json ../solutions/44.json
45.svg: ../problems/45.json ../solutions/45.json
	. venv/bin/activate && python3 vis_prob.py 45.svg ../problems/45.json ../solutions/45.json
46.svg: ../problems/46.json ../solutions/46.json
	. venv/bin/activate && python3 vis_prob.py 46.svg ../problems/46.json ../solutions/46.json
47.svg: ../problems/47.json ../solutions/47.json
	. venv/bin/activate && python3 vis_prob.py 47.svg ../problems/47.json ../solutions/47.json
48.svg: ../problems/48.json ../solutions/48.json
	. venv/bin/activate && python3 vis_prob.py 48.svg ../problems/48.json ../solutions/48.json
49.svg: ../problems/49.json ../solutions/49.json
	. venv/bin/activate && python3 vis_prob.py 49.svg ../problems/49.json ../solutions/49.json
50.svg: ../problems/50.json ../solutions/50.json
	. venv/bin/activate && python3 vis_prob.py 50.svg ../problems/50.json ../solutions/50.json
51.svg: ../problems/51.json ../solutions/51.json
	. venv/bin/activate && python3 vis_prob.py 51.svg ../problems/51.json ../solutions/51.json
52.svg: ../problems/52.json ../solutions/52.json
	. venv/bin/activate && python3 vis_prob.py 52.svg ../problems/52.json ../solutions/52.json
53.svg: ../problems/53.json ../solutions/53.json
	. venv/bin/activate && python3 vis_prob.py 53.svg ../problems/53.json ../solutions/53.json
54.svg: ../problems/54.json ../solutions/54.json
	. venv/bin/activate && python3 vis_prob.py 54.svg ../problems/54.json ../solutions/54.json
55.svg: ../problems/55.json ../solutions/55.json
	. venv/bin/activate && python3 vis_prob.py 55.svg ../problems/55.json ../solutions/55.json
56.svg: ../problems/56.json ../solutions/56.json
	. venv/bin/activate && python3 vis_prob.py 56.svg ../problems/56.json ../solutions/56.json
57.svg: ../problems/57.json ../solutions/57.json
	. venv/bin/activate && python3 vis_prob.py 57.svg ../problems/57.json ../solutions/57.json
58.svg: ../problems/58.json ../solutions/58.json
	. venv/bin/activate && python3 vis_prob.py 58.svg ../problems/58.json ../solutions/58.json
59.svg: ../problems/59.json ../solutions/59.json
	. venv/bin/activate && python3 vis_prob.py 59.svg ../problems/59.json ../solutions/59.json
60.svg: ../problems/60.json ../solutions/60.json
	. venv/bin/activate && python3 vis_prob.py 60.svg ../problems/60.json ../solutions/60.json
61.svg: ../problems/61.json ../solutions/61.json
	. venv/bin/activate && python3 vis_prob.py 61.svg ../problems/61.json ../solutions/61.json
62.svg: ../problems/62.json ../solutions/62.json
	. venv/bin/activate && python3 vis_prob.py 62.svg ../problems/62.json ../solutions/62.json
63.svg: ../problems/63.json ../solutions/63.json
	. venv/bin/activate && python3 vis_prob.py 63.svg ../problems/63.json ../solutions/63.json
64.svg: ../problems/64.json ../solutions/64.json
	. venv/bin/activate && python3 vis_prob.py 64.svg ../problems/64.json ../solutions/64.json
65.svg: ../problems/65.json ../solutions/65.json
	. venv/bin/activate && python3 vis_prob.py 65.svg ../problems/65.json ../solutions/65.json
66.svg: ../problems/66.json ../solutions/66.json
	. venv/bin/activate && python3 vis_prob.py 66.svg ../problems/66.json ../solutions/66.json
67.svg: ../problems/67.json ../solutions/67.json
	. venv/bin/activate && python3 vis_prob.py 67.svg ../problems/67.json ../solutions/67.json
68.svg: ../problems/68.json ../solutions/68.json
	. venv/bin/activate && python3 vis_prob.py 68.svg ../problems/68.json ../solutions/68.json
69.svg: ../problems/69.json ../solutions/69.json
	. venv/bin/activate && python3 vis_prob.py 69.svg ../problems/69.json ../solutions/69.json
70.svg: ../problems/70.json ../solutions/70.json
	. venv/bin/activate && python3 vis_prob.py 70.svg ../problems/70.json ../solutions/70.json
71.svg: ../problems/71.json ../solutions/71.json
	. venv/bin/activate && python3 vis_prob.py 71.svg ../problems/71.json ../solutions/71.json
72.svg: ../problems/72.json ../solutions/72.json
	. venv/bin/activate && python3 vis_prob.py 72.svg ../problems/72.json ../solutions/72.json
73.svg: ../problems/73.json ../solutions/73.json
	. venv/bin/activate && python3 vis_prob.py 73.svg ../problems/73.json ../solutions/73.json
74.svg: ../problems/74.json ../solutions/74.json
	. venv/bin/activate && python3 vis_prob.py 74.svg ../problems/74.json ../solutions/74.json
75.svg: ../problems/75.json ../solutions/75.json
	. venv/bin/activate && python3 vis_prob.py 75.svg ../problems/75.json ../solutions/75.json
76.svg: ../problems/76.json ../solutions/76.json
	. venv/bin/activate && python3 vis_prob.py 76.svg ../problems/76.json ../solutions/76.json
77.svg: ../problems/77.json ../solutions/77.json
	. venv/bin/activate && python3 vis_prob.py 77.svg ../problems/77.json ../solutions/77.json
78.svg: ../problems/78.json ../solutions/78.json
	. venv/bin/activate && python3 vis_prob.py 78.svg ../problems/78.json ../solutions/78.json
79.svg: ../problems/79.json ../solutions/79.json
	. venv/bin/activate && python3 vis_prob.py 79.svg ../problems/79.json ../solutions/79.json
80.svg: ../problems/80.json ../solutions/80.json
	. venv/bin/activate && python3 vis_prob.py 80.svg ../problems/80.json ../solutions/80.json
81.svg: ../problems/81.json ../solutions/81.json
	. venv/bin/activate && python3 vis_prob.py 81.svg ../problems/81.json ../solutions/81.json
82.svg: ../problems/82.json ../solutions/82.json
	. venv/bin/activate && python3 vis_prob.py 82.svg ../problems/82.json ../solutions/82.json
83.svg: ../problems/83.json ../solutions/83.json
	. venv/bin/activate && python3 vis_prob.py 83.svg ../problems/83.json ../solutions/83.json
84.svg: ../problems/84.json ../solutions/84.json
	. venv/bin/activate && python3 vis_prob.py 84.svg ../problems/84.json ../solutions/84.json
85.svg: ../problems/85.json ../solutions/85.json
	. venv/bin/activate && python3 vis_prob.py 85.svg ../problems/85.json ../solutions/85.json
86.svg: ../problems/86.json ../solutions/86.json
	. venv/bin/activate && python3 vis_prob.py 86.svg ../problems/86.json ../solutions/86.json
87.svg: ../problems/87.json ../solutions/87.json
	. venv/bin/activate && python3 vis_prob.py 87.svg ../problems/87.json ../solutions/87.json
88.svg: ../problems/88.json ../solutions/88.json
	. venv/bin/activate && python3 vis_prob.py 88.svg ../problems/88.json ../solutions/88.json
89.svg: ../problems/89.json ../solutions/89.json
	. venv/bin/activate && python3 vis_prob.py 89.svg ../problems/89.json ../solutions/89.json
90.svg: ../problems/90.json ../solutions/90.json
	. venv/bin/activate && python3 vis_prob.py 90.svg ../problems/90.json ../solutions/90.json
